org.nrg.Feature=Rollback
org.nrg.Feature.Rollback.key=Rollback
org.nrg.Feature.Rollback.name=Rollback
org.nrg.Feature.Rollback.OnByDefault=false
org.nrg.Feature.Rollback.description= Allows users to perform version rollback