/*
 * build.gradle
 * Copyright 2018 Radiologics, Inc
 * Developer: James Ransford
 */
 
def pluginName = 'esign_plugin'
def groupName = 'com.radiologics'
def pluginVersion = '1.1.0-SNAPSHOT'

group groupName
version pluginVersion

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: "maven-publish"
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.github.jk1.dependency-license-report'


buildscript {
    ext {
        vXnat = "1.9.0-RC-SNAPSHOT"
    }
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
        mavenLocal()
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:1.0.6.RELEASE"
    	classpath 'com.github.jk1:gradle-license-report:1.16'
    }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenLocal()
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
    mavenCentral()
}

dependencyManagement.imports {
    mavenBom "org.nrg:parent:${vXnat}"
}

dependencies {
    implementation ("org.nrg.xnat:web"){
        exclude group: '*'
    }
    
    implementation ("org.nrg.xdat:core"){
        exclude group: '*'
    }

    implementation "org.nrg.xnat:xnat-data-models"
    implementation "commons-collections:commons-collections"
    implementation "commons-io:commons-io"
    implementation "javax.mail:javax.mail-api"
    implementation "org.springframework:spring-jdbc"
    
}

publishing {
	publications {
		maven(MavenPublication) {
			groupId = groupName
			artifactId = pluginName
			version = pluginVersion
			from components.java
		}
	}
}

idea {
    module {
        inheritOutputDirs = false
        outputDir = compileJava.destinationDir
        testOutputDir = compileTestJava.destinationDir
    }
}
